services:
  postgres:
    image: postgres:16
    container_name: cis_postgres
    environment:
      POSTGRES_USER: admeanie
      POSTGRES_PASSWORD: assword
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
